#! /bin/sh

"exec" "python3" "${0}" "${@}"

import sys
from os import unlink, access, F_OK
from subprocess import Popen, PIPE
import re
import linecache

COMPILER = "g++"
COMPILER_ALT = "clang++"
OK_STATUS = 0
NO_MORE_BUGS_STATUS = 1
WRONG_STATUS = 2
verbose = 0

def msg( str, nonl = False ):
	if ( verbose ):
		print( str, end = "" )
		if ( not nonl ):
			print( "" )

def has_opt( opts, short, long ):
	return ( opts.count( short ) + opts.count( long ) )

def erase_opt( opts, short, long ):
	if ( opts.count( short ) > 0 ):
		opts.remove( short )
	if ( opts.count( long ) > 0 ):
		opts.remove( long )

def get_output_path_index( opts ):
	has = 0
	output_path_index = 0
	for opt in opts:
		if ( has == 1 ):
			output_path_index += 1
			break
		if ( opt == "-o" ):
			has = 1
		output_path_index += 1
	return output_path_index

def get_input_path( opts ):
	input_path_match = re.compile( "^[\\w/\\.-]+\.acxx$" )
	input_path = ""
	for opt in opts:
		if input_path_match.match( opt ):
			input_path = opt
			break
	if ( input_path == "" ):
		raise Exception( "no input path found" )
	return input_path

def verify_bug( input_path, line_no ):
	line = linecache.getline( input_path, int( line_no ) )
	fail_here_match = re.compile( "\\bMUST_FAIL_HERE\\b" )
	match = fail_here_match.search( line )
	status = WRONG_STATUS
	if ( match ):
		status = OK_STATUS
	return status

def check_bug( lines, input_path ):
	no_more_bugs_match = re.compile( "^" + input_path + "(:[0-9]+)+: error:( #error)? NO_SUCH_BUG$" )
	line_number_match = re.compile( "^" + input_path + ":([0-9]+):([0-9]+:)* +(error|note|required from |instantiated from)" )
	required_from_here = re.compile( "^" + input_path + ":([0-9]+):([0-9]+:)* +required from " )
	ret = WRONG_STATUS
	for line in lines:
		msg( line, True )
		if ( ret == WRONG_STATUS ):
			match = no_more_bugs_match.match( line )
			if ( match ):
				ret = NO_MORE_BUGS_STATUS
				break
			else:
				match = line_number_match.match( line )
				if ( match ):
					ret = verify_bug( input_path, match.group( 1 ) )
					if ( ret == WRONG_STATUS ) and required_from_here.match( line ):
						continue
					break
	return ret

def acxx( argv ):
	try:
		if ( has_opt( argv, "-h", "--help" ) ):
			print( "acxx -o output/path/object.ao some/dir/source.acxx" )
			print( "options:" )
			print( "-o, --output output/path/object.ao - output path for ao files" )
			print( "-h, --help - this help screen" )
			print( "-v, --verbose - print some informational messages" )
			return
		if ( not has_opt( argv, "-o", "--output" ) ):
			raise Exception( "Output path option required and not specified" )
		global verbose
		verbose = has_opt( argv, "-v", "--verbose" )
		erase_opt( argv, "-v", "--verbose" )
		output_path = argv[ get_output_path_index( argv ) - 1 ]
		input_path = get_input_path( sys.argv[1:] )
		msg( "source file is: " + input_path )
		msg( "output path is: " + output_path )
		if ( access( output_path, F_OK ) ):
			unlink( output_path )
		BUG_TEMPLATE = "BUG_"
		bug_status = OK_STATUS
		bug_no = 0
		lines = 0
		while ( bug_status == OK_STATUS ):
			msg( "################ processing bug no: " + str( bug_no ) + " ################" )
			try:
				msg( COMPILER + " -xc++" + " -D" + BUG_TEMPLATE + str( bug_no ) + " " + " ".join( argv ) )
				out = Popen( [ COMPILER, "-xc++", "-D" + BUG_TEMPLATE + str( bug_no ) ] + argv, stderr = PIPE ).stderr;
			except:
				msg( COMPILER_ALT + " -xc++" + " -D" + BUG_TEMPLATE + str( bug_no ) + " " + " ".join( argv ) )
				out = Popen( [ COMPILER_ALT, "-xc++", "-D" + BUG_TEMPLATE + str( bug_no ) ] + argv, stderr = PIPE ).stderr;
			lines = map( lambda x: x.decode(), out.readlines() )
			bug_status = check_bug( lines, input_path )
			out.close()
			bug_no += 1
		if ( access( output_path, F_OK ) ):
			unlink( output_path )
		if ( bug_status == WRONG_STATUS ):
			print( sys.stderr, "Anti-compilation of BUG number " + str( bug_no - 1 ) + " failed!", file = sys.stderr )
			print( "\n".join( lines ) )
		else:
			f = open( output_path, 'w' )
			f.close()
	except Exception as e:
		print( e )

def main():
	acxx( sys.argv[1:] )
#	learn()

if __name__ == "__main__":
	main()
