#! /usr/bin/env python

import sys

try:
	import subprocess
except:
	print "Importing `subprocess' module failed!"
	sys.exit( 1 )

try:
	import pygtk
	pygtk.require( "2.0" )
	import pango
	import gtk
	import gtk.glade
except:
	print "GTK/Pango/Glade not availible!"
	sys.exit( 1 )

class GTress:
	def __init__( self ):
		self._gui = gtk.glade.XML( "gtress.xrc" )
		signals = {
			"destroy" : self.destroy,
			"delete_event" : self.delete_event
		}
		self._gui.signal_autoconnect( signals )
		self._list = self._gui.get_widget( "GUI_LIST" )
		self._data = gtk.ListStore( str, int, bool )
		self._listSuiteNameColumn = gtk.TreeViewColumn( "suite names" )
		self._listSuiteNameCellRenderer = gtk.CellRendererText()
		self._listSuiteNameColumn.pack_start( self._listSuiteNameCellRenderer, True )
		self._listSuiteNameColumn.add_attribute( self._listSuiteNameCellRenderer, "text", 0 )
		self._listSuiteNameColumn.set_sizing( gtk.TREE_VIEW_COLUMN_AUTOSIZE )
		self._listSuiteNameColumn.set_resizable( True )
		self._listSuiteNameColumn.set_expand( True )
	
		self._listTestCountColumn = gtk.TreeViewColumn( "test count" )
		self._listTestCountCellRenderer = gtk.CellRendererText()
		self._listTestCountCellRenderer.set_property( "xalign", 1 )
		self._listTestCountCellRenderer.set_property( "xpad", 8 )
		self._listTestCountColumn.pack_start( self._listTestCountCellRenderer, True )
		self._listTestCountColumn.add_attribute( self._listTestCountCellRenderer, "text", 1 )
		self._listTestCountColumn.set_sizing( gtk.TREE_VIEW_COLUMN_FIXED )
		self._listTestCountColumn.set_fixed_width( 80 )
		self._listTestCountColumn.set_resizable( False )
		self._listTestCountColumn.set_expand( False )

		self._listSuiteEnabledColumn = gtk.TreeViewColumn( "enabled" )
		self._listSuiteEnabledCellRenderer = gtk.CellRendererToggle()
		self._listSuiteEnabledCellRenderer.set_property( "activatable", True )
		self._listSuiteEnabledCellRenderer.set_property( "xalign", 0.5 )
		self._listSuiteEnabledColumn.pack_start( self._listSuiteEnabledCellRenderer, True )
		self._listSuiteEnabledColumn.add_attribute( self._listSuiteEnabledCellRenderer, "active", 2 )
		self._listSuiteEnabledCellRenderer.connect( "toggled", self.col1_toggled_cb, self._data )
		self._listSuiteEnabledColumn.set_sizing( gtk.TREE_VIEW_COLUMN_FIXED )
		self._listSuiteEnabledColumn.set_fixed_width( 64 )
		self._listSuiteEnabledColumn.set_resizable( False )
		self._listSuiteEnabledColumn.set_expand( False )

		self._list.append_column( self._listSuiteNameColumn )
		self._list.append_column( self._listTestCountColumn )
		self._list.append_column( self._listSuiteEnabledColumn )
		self._list.set_model( self._data )
		tests = subprocess.Popen( [ "./build/debug/tress/1exec", "-L", "-v" ], stdout = subprocess.PIPE ).stdout
		total = 0;
		for line in tests.readlines():
			fields = line.lstrip( " \t" ).strip( "\n" ).split()
			if ( fields[0] != "setup._argc" ) and ( fields[0] != "setup._argv[0]" ) and ( fields[0] != "total" ):
				total += int( fields[1] )
				self._data.append( [ fields[0], int( fields[1] ), False ] )
		self._totalTestCount = self._gui.get_widget( "GUI_TOTAL_TEST_COUNT" )
		self._totalEnabledSuites = self._gui.get_widget( "GUI_TOTAL_ENABLED_SUITES" )
		self._totalTestCount.set_text( str( total ) )

	def col1_toggled_cb( self, cell, path, model ):
		model[path][2] = not model[path][2]
		return

	def main( self ):
		gtk.main()

	def delete_event( self, widget, data = None ):
		return False

	def destroy( self, widget, data = None ):
		gtk.main_quit()

if __name__ == "__main__":
	gtress = GTress()
	gtress.main()

