#! /bin/sh

set -eu

if [ ! -f _aux/set-limits.sh ] ; then
	echo "This script must be executed direclty from \`tress\` root directory."
	exit 1
fi

. ./_aux/set-limits.sh

exec ./build/debug/tress/1exec "${@}"
