#! /bin/sh

LOG_FILE="./out/hpipedchild.log"

log( ) {
	echo "[`date`]: ${@}" >> ${LOG_FILE}
}

/bin/rm -f ${LOG_FILE}

log "child start ..."

read LINE

log "read input: ${LINE}"

case "${LINE}" in
	"out")
		echo "hello-OUT" > /dev/stdout
	;;
	"err")
		echo "hello-ERR" > /dev/stderr
	;;
	*)
		echo "error" > /dev/stdout
		echo "error" > /dev/stderr
	;;
esac

log "written output ..."
log "exiting"

exit 0
