#! /bin/sh

LOG_FILE="./out/hpipedchild.log"

log( ) {
	echo "[`date`]: ${@}" >> ${LOG_FILE}
}

/bin/rm -f ${LOG_FILE}

log "child start ..."

limit=1
i=0
if [ ${#} -gt 0 ] ; then
	limit=${1}
fi

ret=0
while read LINE ; do

	log "read input: ${LINE}"

	case "${LINE}" in
		"out")
			echo "hello-OUT"
		;;
		"err")
			echo "hello-ERR" >&2
			ret=7
		;;
		*)
			echo "error"
			echo "error" >&2
			ret=13
		;;
	esac
	i=$((${i} + 1))
	if [ ${i} -ge ${limit} ] ; then
		break
	fi

done

log "written output ..."
log "exiting"

exit ${ret}
