#ifndef TRESS_LOCAL_HXX_INCLUDED
#define TRESS_LOCAL_HXX_INCLUDED 1

#ifdef TRESS_CONFIG_HXX_INCLUDED
#define SIZEOF_CHTYPE @SIZEOF_CHTYPE@
#define CONTINUOUS_INTEGRATION_@CONTINUOUS_INTEGRATION_SYSTEM@ 1
#cmakedefine HAVE_SGI_STL_EXTENSIONS
#cmakedefine01 HAVE_DECL_RTLD_NEXT
#endif /* #ifdef TRESS_CONFIG_HXX_INCLUDED */

#endif /* #ifndef TRESS_LOCAL_HXX_INCLUDED */

